env: local
grpc:
  port: 8002
  timeout: 5s
db:
  host: localhost
  port: 6379
  password: "00000000"
  db: 0
auth:
  accessTokenTTL: 30m
  refreshTokenTTL: 360h # 15 days
  secretKey: "superSecretKey"
userService:
  host: localhost
  port: 8000