env: local
grpc:
  port: 8001
db:
  host: localhost
  port: 27017
kafka:
  address: "localhost:9092,localhost:9093,localhost:9094"
  userServiceTopic: "user-service"
  consumerGroup: "article-service"